# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
