# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180712_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AddField(
            model_name='location',
            name='loc',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Zurich', 'Zurich'), ('Paris', 'Paris'), ('Munich', 'Munich'), ('Tokyo', 'Tokyo'), ('London', 'London'), ('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Berlin', 'Berlin')], default=11, max_length=255),
            preserve_default=False,
        ),
    ]
